"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, Pencil, Package } from "lucide-react";
import { modules, moduleNames } from "@/src/data/warehouse-data";
import type { ModuleKey } from "@/src/types/warehouse";
import type { DataRow } from "@/src/types/warehouse";
import { StatusBadge } from "@/src/components/warehouse/ui";
import { getDispatches, getHistory, getInventory, getPending, getProducts, getReceiptDraft, getReceipts, getTransferDraft, getTransfers, getWarehouseOptions, updateReceiptDraft, updateTransferDraft, type SupplierOption, type WarehouseOption } from "@/src/lib/warehouse-api";

export default function DetailView({ section, id, edit = false }: { section: string; id: string; edit?: boolean }) {
  const router = useRouter(); const [saved, setSaved] = useState(false); const [apiRow, setApiRow] = useState<DataRow | null>(null); const [loading, setLoading] = useState(false); const [apiError, setApiError] = useState("");
  const definition = modules[section as ModuleKey];
  useEffect(() => {
    if (!definition || !["inventory", "products", "receipts", "transfers", "dispatches", "pending", "history"].includes(section)) return;
    let cancelled = false; setLoading(true); setApiError("");
    const load = section === "inventory" ? getInventory().then(result => result.items.map(item => ({ id: item.sku, name: item.product_name, code: `${item.sku} · ${item.unit}`, location: item.location ?? "—", quantity: item.quantity, status: item.status })))
      : section === "products" ? getProducts() : section === "receipts" ? getReceipts() : section === "transfers" ? getTransfers() : section === "dispatches" ? getDispatches() : section === "pending" ? getPending() : getHistory();
    load.then(rows => { if (!cancelled) setApiRow(rows.find(row => row.id === id) ?? null); }).catch(error => { if (!cancelled) setApiError(error instanceof Error ? error.message : "Không thể tải chi tiết."); }).finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [definition, id, section]);
  if (!definition || loading) return <div className="auth-loading">{loading ? "Đang tải chi tiết…" : "Không tìm thấy bản ghi"}</div>;
  const row = apiRow ?? definition.rows.find(item => item.id === id);
  if (!row) return <div className="not-found"><Package size={22}/><h1>Không tìm thấy bản ghi</h1><p>{apiError || "Bản ghi không tồn tại hoặc không thuộc kho được phân quyền."}</p><Link href={`/${section}`} className="button">Quay lại danh sách</Link></div>;
  if (edit && apiRow && (section === "receipts" || section === "transfers") && Number.isInteger(Number(apiRow.recordId))) return <DraftEditor section={section} id={Number(apiRow.recordId)} onDone={() => router.push(`/${section}/${id}`)} />;
  const fields = Object.entries(row).filter(([key]) => key !== "code");
  return <><div className="page-heading"><div><Link className="back-link" href={`/${section}`}><ArrowLeft size={14}/> {moduleNames[section as ModuleKey]}</Link><h1>{edit ? `Chỉnh sửa ${row.id}` : `Chi tiết ${row.id}`}</h1></div><div className="detail-actions"><Link className="button" href={`/${section}`}><ArrowLeft size={14}/> Quay lại</Link><Link className="button primary" href={`/${section}/${id}/edit`}><Pencil size={14}/> Chỉnh sửa</Link></div></div>
    <section className="form-panel"><div className="form-panel-head"><h2>Thông tin {moduleNames[section as ModuleKey]?.toLocaleLowerCase("vi")}</h2><p>Mã bản ghi <strong>{id}</strong></p></div>{apiError && <div className="module-note">Không tải được dữ liệu live: {apiError}</div>}{edit && apiRow && <div className="module-note">Bản ghi live chỉ được thay đổi qua workflow nghiệp vụ; chưa mở chỉnh sửa trực tiếp để tránh sai tồn kho.</div>}{edit && !apiRow ? <form onSubmit={event => { event.preventDefault(); setSaved(true); window.setTimeout(() => router.push(`/${section}/${id}`), 900); }}><div className="form-grid">{fields.map(([key, value]) => <label key={key}><span>{definition.columns.find(col => col.key === key)?.label ?? key.toLocaleUpperCase("vi")}</span><input defaultValue={String(value)} readOnly={key === "id"} /></label>)}</div><div className="form-actions"><Link className="button" href={`/${section}/${id}`}>Hủy</Link><button className="button primary" type="submit">{saved ? "Đã lưu" : "Lưu thay đổi"}</button></div></form> : <div className="detail-grid">{fields.map(([key, value]) => <div className="detail-field" key={key}><span>{definition.columns.find(col => col.key === key)?.label ?? key.toLocaleUpperCase("vi")}</span>{key === "status" ? <StatusBadge value={value}/> : <strong>{value}</strong>}</div>)}</div>}</section></>;
}

function DraftEditor({ section, id, onDone }: { section: string; id: number; onDone: () => void }) {
  const receipt = section === "receipts"; const [options, setOptions] = useState<{ warehouses: WarehouseOption[]; suppliers: SupplierOption[] }>({ warehouses: [], suppliers: [] }); const [draft, setDraft] = useState<any>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => { Promise.all([getWarehouseOptions(), receipt ? getReceiptDraft(id) : getTransferDraft(id)]).then(([nextOptions, nextDraft]) => { setOptions(nextOptions); setDraft(nextDraft); }).catch(err => setError(err instanceof Error ? err.message : "Không tải được phiếu.")); }, [id, receipt]);
  if (error) return <div className="not-found"><Package size={22}/><h1>Không thể sửa phiếu</h1><p>{error}</p><Link href={`/${section}/${id}`} className="button">Quay lại</Link></div>;
  if (!draft) return <div className="auth-loading">Đang tải dữ liệu chỉnh sửa…</div>;
  const lineText = draft.lines.map((line: { sku: string; quantity: number; unit_price?: number }) => receipt ? `${line.sku}:${line.quantity}:${line.unit_price ?? 0}` : `${line.sku}:${line.quantity}`).join(", ");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setSaving(true); const form = new FormData(event.currentTarget); try { const lines = String(form.get("items") ?? "").split(",").map(item => item.trim()).filter(Boolean).map(item => { const parts = item.split(":").map(value => value.trim()); const quantity = Number(parts[1]); const price = Number(parts[2] ?? 0); if (!parts[0] || !Number.isInteger(quantity) || quantity <= 0 || (receipt && (!Number.isFinite(price) || price < 0))) throw new Error(receipt ? "Dòng nhập phải có dạng SKU:Số lượng:Đơn giá." : "Dòng chuyển phải có dạng SKU:Số lượng."); return receipt ? { sku: parts[0], quantity, unit_price: price } : { sku: parts[0], quantity }; }); if (!lines.length) throw new Error("Phiếu phải có ít nhất một dòng hàng."); if (receipt) await updateReceiptDraft(id, { supplier_id: Number(form.get("supplier")), warehouse_id: Number(form.get("warehouse")), note: String(form.get("note") ?? "") || undefined, lines: lines as { sku: string; quantity: number; unit_price: number }[] }); else await updateTransferDraft(id, { source_warehouse_id: Number(form.get("from")), destination_warehouse_id: Number(form.get("to")), note: String(form.get("note") ?? "") || undefined, lines: lines as { sku: string; quantity: number }[] }); setSaved(true); window.setTimeout(onDone, 500); } catch (err) { setError(err instanceof Error ? err.message : "Không thể lưu phiếu."); } finally { setSaving(false); } }
  return <><div className="page-heading"><div><Link className="back-link" href={`/${section}/${id}`}><ArrowLeft size={14}/> Chi tiết phiếu</Link><h1>Chỉnh sửa phiếu</h1></div></div><section className="form-panel"><div className="form-panel-head"><h2>Chỉnh sửa phiếu nháp</h2><p>Cập nhật header và dòng hàng trong cùng một transaction.</p></div>{error && <div className="module-note">{error}</div>}{saved && <div className="module-note">Đã lưu phiếu nháp.</div>}<form onSubmit={submit}><div className="form-grid"><label><span>{receipt ? "Nhà cung cấp" : "Kho xuất"}</span><select name={receipt ? "supplier" : "from"} defaultValue={String(receipt ? draft.supplier_id : draft.source_warehouse_id)} required>{(receipt ? options.suppliers : options.warehouses).map((item: SupplierOption | WarehouseOption) => <option key={receipt ? (item as SupplierOption).ma_ncc : (item as WarehouseOption).ma_kho} value={String(receipt ? (item as SupplierOption).ma_ncc : (item as WarehouseOption).ma_kho)}>{receipt ? (item as SupplierOption).ten_ncc : (item as WarehouseOption).ten_kho}</option>)}</select></label><label><span>{receipt ? "Kho nhập" : "Kho nhận"}</span><select name={receipt ? "warehouse" : "to"} defaultValue={String(receipt ? draft.warehouse_id : draft.destination_warehouse_id)} required>{options.warehouses.map(item => <option key={item.ma_kho} value={item.ma_kho}>{item.ten_kho}</option>)}</select></label><label className="wide"><span>Sản phẩm và số lượng</span><input name="items" defaultValue={lineText} required /></label><label className="wide"><span>Ghi chú</span><textarea name="note" defaultValue={draft.note} /></label></div><div className="form-actions"><Link className="button" href={`/${section}/${id}`}>Hủy</Link><button className="button primary" disabled={saving} type="submit">{saving ? "Đang lưu…" : "Lưu thay đổi"}</button></div></form></section></>;
}
