-- Initial schema for a NEW, EMPTY Supabase database only.
-- Review first. This is not an upgrade script for an existing database.
-- Never drop existing tables to run this migration.
begin;

create table public."KHO" (
  "ma_kho" int generated by default as identity primary key,
  "ten_kho" varchar not null,
  "dia_chi" varchar not null,
  "trang_thai" int not null default 1
);

create table public."NHAN_VIEN" (
  "ma_nhan_vien" varchar primary key,
  "ma_kho" int,
  "loai_nhan_vien" varchar not null,
  "ho_ten" varchar not null,
  "cccd" varchar unique,
  "email" varchar,
  "sdt" varchar,
  "luong" decimal(18,2),
  "trang_thai" int not null default 1,
  check (loai_nhan_vien IN ('ADMIN', 'THU_KHO')),
  check ((loai_nhan_vien = 'ADMIN' AND ma_kho IS NULL) OR (loai_nhan_vien = 'THU_KHO' AND ma_kho IS NOT NULL))
);

create table public."TAI_KHOAN" (
  "ma_tk" varchar primary key,
  "ten_tai_khoan" varchar not null unique,
  "email" varchar unique,
  "mat_khau_hash" varchar not null,
  "ma_kh" varchar unique,
  "ma_nhan_vien" varchar unique,
  "trang_thai" int not null default 1,
  check ((ma_kh IS NOT NULL AND ma_nhan_vien IS NULL) OR (ma_kh IS NULL AND ma_nhan_vien IS NOT NULL))
);

create table public."KHACH_HANG" (
  "ma_kh" varchar primary key,
  "ten_kh" varchar not null,
  "sdt" varchar,
  "dia_chi_chi_tiet_md" varchar,
  "tinh_thanh_md" varchar,
  "xa_phuong_md" varchar
);

create table public."LOAI_SP" (
  "ma_loai_sp" varchar primary key,
  "ten_loai_sp" varchar not null unique,
  "trang_thai" int not null default 1
);

create table public."SAN_PHAM" (
  "ma_sp" varchar primary key,
  "sku" varchar not null unique,
  "ten_sp" varchar not null,
  "ma_loai_sp" varchar not null,
  "thuong_hieu" varchar,
  "gia_ban_hien_tai" decimal(18,2) not null,
  "mo_ta" text,
  "thong_so_ky_thuat" text,
  "don_vi" varchar not null default 'Cai',
  "bao_hanh_thang" int not null default 0,
  "duong_dan_anh" varchar,
  "trang_thai" int not null default 1,
  check (gia_ban_hien_tai >= 0),
  check (bao_hanh_thang >= 0)
);

create table public."TON_KHO" (
  "ma_kho" int not null,
  "sku" varchar not null,
  "so_luong_ton" int not null default 0 check (so_luong_ton >= 0),
  "cap_nhat_luc" timestamptz,
  primary key ("ma_kho", "sku")
);

create table public."NHA_CUNG_CAP" (
  "ma_ncc" int generated by default as identity primary key,
  "ten_ncc" varchar not null,
  "sdt" varchar,
  "email" varchar,
  "dia_chi" varchar,
  "trang_thai" int not null default 1
);

create table public."PHIEU_NHAP" (
  "ma_phieu_nhap" int generated by default as identity primary key,
  "ma_phieu_code" varchar not null unique,
  "ma_ncc" int not null,
  "ma_kho" int not null,
  "ngay_tao" timestamptz not null,
  "ngay_nhap" timestamptz,
  "trang_thai" varchar not null default 'NHAP',
  "nguoi_tao" varchar not null,
  "nguoi_cap_nhat" varchar,
  "nguoi_xac_nhan" varchar,
  "ghi_chu" text
);

create table public."CT_PHIEU_NHAP" (
  "ma_phieu_nhap" int not null,
  "sku" varchar not null,
  "so_luong_nhap" int not null check (so_luong_nhap > 0),
  "gia_nhap" decimal(18,2) not null check (gia_nhap >= 0),
  primary key ("ma_phieu_nhap", "sku")
);

create table public."PHIEU_CHUYEN_KHO" (
  "ma_phieu_chuyen" int generated by default as identity primary key,
  "ma_kho_xuat" int not null,
  "ma_kho_nhan" int not null,
  "ngay_tao" timestamptz not null,
  "ngay_xuat" timestamptz,
  "ngay_nhan" timestamptz,
  "trang_thai" varchar not null default 'NHAP',
  "nguoi_tao" varchar not null,
  "nguoi_xuat" varchar,
  "nguoi_nhan" varchar,
  "ghi_chu" text,
  check (ma_kho_xuat <> ma_kho_nhan)
);

create table public."CT_CHUYEN_KHO" (
  "ma_phieu_chuyen" int not null,
  "sku" varchar not null,
  "so_luong" int not null check (so_luong > 0),
  primary key ("ma_phieu_chuyen", "sku")
);

create table public."DON_HANG" (
  "ma_donhang" varchar primary key,
  "ma_kh" varchar,
  "ma_nhan_vien" varchar,
  "kenh_ban" varchar not null,
  "trang_thai" varchar not null default 'MOI',
  "thoi_gian_dat" timestamptz not null,
  "thoi_gian_xuat_kho" timestamptz,
  "thoi_gian_hoan_thanh" timestamptz,
  "ten_nguoi_nhan" varchar,
  "sdt_nguoi_nhan" varchar,
  "dia_chi_chi_tiet" varchar,
  "tinh_thanh" varchar,
  "xa_phuong" varchar,
  "ghi_chu" text
);

create table public."CT_DON_HANG" (
  "ma_ct_donhang" int generated by default as identity primary key,
  "ma_donhang" varchar not null,
  "sku" varchar not null,
  "ma_kho_xuat" int not null,
  "ten_sp_luc_ban" varchar not null,
  "don_vi_luc_ban" varchar not null,
  "so_luong" int not null check (so_luong > 0),
  "don_gia" decimal(18,2) not null,
  "giam_gia" decimal(18,2) not null default 0,
  "giam_gia_voucher" decimal(18,2) not null default 0,
  "thue_suat" decimal(5,2) not null,
  "tien_thue" decimal(18,2) not null,
  "thanh_tien" decimal(18,2) not null,
  check (don_gia >= 0 AND giam_gia >= 0 AND giam_gia_voucher >= 0 AND giam_gia + giam_gia_voucher <= so_luong * don_gia),
  check (thue_suat >= 0 AND thue_suat <= 100 AND tien_thue >= 0),
  check (thanh_tien = so_luong * don_gia - giam_gia - giam_gia_voucher + tien_thue)
);

create table public."HOA_DON" (
  "ma_hoadon" varchar primary key,
  "ma_donhang" varchar not null unique,
  "thoi_gian_lap" timestamptz not null,
  "ten_nguoi_mua" varchar,
  "ma_so_thue" varchar,
  "dia_chi_nguoi_mua" varchar,
  "tong_tien_giam" decimal(18,2) not null default 0,
  "tong_tien_truoc_thue" decimal(18,2) not null,
  "tong_tien_thue" decimal(18,2) not null,
  "tong_tien_sau_thue" decimal(18,2) not null,
  "nguoi_lap" varchar not null,
  check (tong_tien_giam >= 0),
  check (tong_tien_truoc_thue >= 0 AND tong_tien_thue >= 0 AND tong_tien_sau_thue >= 0),
  check (tong_tien_sau_thue = tong_tien_truoc_thue + tong_tien_thue)
);

create table public."THANH_TOAN" (
  "ma_thanh_toan" int generated by default as identity primary key,
  "ma_donhang" varchar not null,
  "so_tien" decimal(18,2) not null check (so_tien > 0),
  "loai_giao_dich" varchar not null default 'THU',
  "phuong_thuc" varchar not null,
  "trang_thai" varchar not null,
  "ma_giao_dich" varchar unique,
  "thoi_gian" timestamptz not null
);

create table public."CHUONG_TRINH_KHUYEN_MAI" (
  "ma_ctkm" int generated by default as identity primary key,
  "ten_chuong_trinh" varchar not null,
  "mo_ta" text,
  "ngay_bat_dau" timestamptz not null,
  "ngay_ket_thuc" timestamptz not null,
  "trang_thai" varchar not null default 'NHAP',
  "nguoi_tao" varchar not null,
  "ngay_tao" timestamptz not null,
  check (ngay_ket_thuc > ngay_bat_dau),
  check (trang_thai IN ('NHAP', 'HOAT_DONG', 'TAM_DUNG', 'KET_THUC'))
);

create table public."VOUCHER" (
  "ma_voucher" int generated by default as identity primary key,
  "ma_ctkm" int not null,
  "ma_code" varchar not null unique,
  "loai_giam" varchar not null,
  "gia_tri_giam" decimal(18,2) not null,
  "giam_toi_da" decimal(18,2),
  "gia_tri_don_toi_thieu" decimal(18,2) not null default 0,
  "gioi_han_tong_luot" int,
  "gioi_han_moi_khach" int not null default 1,
  "trang_thai" varchar not null default 'HOAT_DONG',
  "ngay_tao" timestamptz not null,
  check (loai_giam IN ('PHAN_TRAM', 'SO_TIEN')),
  check (gia_tri_giam > 0 AND (loai_giam <> 'PHAN_TRAM' OR gia_tri_giam <= 100)),
  check (giam_toi_da IS NULL OR (loai_giam = 'PHAN_TRAM' AND giam_toi_da > 0)),
  check (gia_tri_don_toi_thieu >= 0),
  check (gioi_han_tong_luot IS NULL OR gioi_han_tong_luot > 0),
  check (gioi_han_moi_khach > 0),
  check (trang_thai IN ('HOAT_DONG', 'TAM_DUNG'))
);

create table public."SU_DUNG_VOUCHER" (
  "ma_su_dung" int generated by default as identity primary key,
  "ma_voucher" int not null,
  "ma_donhang" varchar not null unique,
  "so_tien_giam" decimal(18,2) not null check (so_tien_giam > 0),
  "thoi_gian_ap_dung" timestamptz not null,
  "trang_thai" varchar not null default 'DA_AP_DUNG',
  "thoi_gian_huy" timestamptz,
  check ((trang_thai = 'DA_AP_DUNG' AND thoi_gian_huy IS NULL) OR (trang_thai = 'DA_HUY' AND thoi_gian_huy IS NOT NULL))
);

alter table public."NHAN_VIEN" add constraint "fk_0_NHAN_VIEN" foreign key ("ma_kho") references public."KHO" ("ma_kho");
alter table public."TAI_KHOAN" add constraint "fk_1_TAI_KHOAN" foreign key ("ma_kh") references public."KHACH_HANG" ("ma_kh");
alter table public."TAI_KHOAN" add constraint "fk_2_TAI_KHOAN" foreign key ("ma_nhan_vien") references public."NHAN_VIEN" ("ma_nhan_vien");
alter table public."SAN_PHAM" add constraint "fk_3_SAN_PHAM" foreign key ("ma_loai_sp") references public."LOAI_SP" ("ma_loai_sp");
alter table public."TON_KHO" add constraint "fk_4_TON_KHO" foreign key ("ma_kho") references public."KHO" ("ma_kho");
alter table public."TON_KHO" add constraint "fk_5_TON_KHO" foreign key ("sku") references public."SAN_PHAM" ("sku");
alter table public."PHIEU_NHAP" add constraint "fk_6_PHIEU_NHAP" foreign key ("ma_ncc") references public."NHA_CUNG_CAP" ("ma_ncc");
alter table public."PHIEU_NHAP" add constraint "fk_7_PHIEU_NHAP" foreign key ("ma_kho") references public."KHO" ("ma_kho");
alter table public."PHIEU_NHAP" add constraint "fk_8_PHIEU_NHAP" foreign key ("nguoi_tao") references public."NHAN_VIEN" ("ma_nhan_vien");
alter table public."PHIEU_NHAP" add constraint "fk_9_PHIEU_NHAP" foreign key ("nguoi_cap_nhat") references public."NHAN_VIEN" ("ma_nhan_vien");
alter table public."PHIEU_NHAP" add constraint "fk_10_PHIEU_NHAP" foreign key ("nguoi_xac_nhan") references public."NHAN_VIEN" ("ma_nhan_vien");
alter table public."CT_PHIEU_NHAP" add constraint "fk_11_CT_PHIEU_NHAP" foreign key ("ma_phieu_nhap") references public."PHIEU_NHAP" ("ma_phieu_nhap");
alter table public."CT_PHIEU_NHAP" add constraint "fk_12_CT_PHIEU_NHAP" foreign key ("sku") references public."SAN_PHAM" ("sku");
alter table public."PHIEU_CHUYEN_KHO" add constraint "fk_13_PHIEU_CHUYEN_KHO" foreign key ("ma_kho_xuat") references public."KHO" ("ma_kho");
alter table public."PHIEU_CHUYEN_KHO" add constraint "fk_14_PHIEU_CHUYEN_KHO" foreign key ("ma_kho_nhan") references public."KHO" ("ma_kho");
alter table public."PHIEU_CHUYEN_KHO" add constraint "fk_15_PHIEU_CHUYEN_KHO" foreign key ("nguoi_tao") references public."NHAN_VIEN" ("ma_nhan_vien");
alter table public."PHIEU_CHUYEN_KHO" add constraint "fk_16_PHIEU_CHUYEN_KHO" foreign key ("nguoi_xuat") references public."NHAN_VIEN" ("ma_nhan_vien");
alter table public."PHIEU_CHUYEN_KHO" add constraint "fk_17_PHIEU_CHUYEN_KHO" foreign key ("nguoi_nhan") references public."NHAN_VIEN" ("ma_nhan_vien");
alter table public."CT_CHUYEN_KHO" add constraint "fk_18_CT_CHUYEN_KHO" foreign key ("ma_phieu_chuyen") references public."PHIEU_CHUYEN_KHO" ("ma_phieu_chuyen");
alter table public."CT_CHUYEN_KHO" add constraint "fk_19_CT_CHUYEN_KHO" foreign key ("sku") references public."SAN_PHAM" ("sku");
alter table public."DON_HANG" add constraint "fk_20_DON_HANG" foreign key ("ma_kh") references public."KHACH_HANG" ("ma_kh");
alter table public."DON_HANG" add constraint "fk_21_DON_HANG" foreign key ("ma_nhan_vien") references public."NHAN_VIEN" ("ma_nhan_vien");
alter table public."CT_DON_HANG" add constraint "fk_22_CT_DON_HANG" foreign key ("ma_donhang") references public."DON_HANG" ("ma_donhang");
alter table public."CT_DON_HANG" add constraint "fk_23_CT_DON_HANG" foreign key ("sku") references public."SAN_PHAM" ("sku");
alter table public."CT_DON_HANG" add constraint "fk_24_CT_DON_HANG" foreign key ("ma_kho_xuat") references public."KHO" ("ma_kho");
alter table public."HOA_DON" add constraint "fk_25_HOA_DON" foreign key ("ma_donhang") references public."DON_HANG" ("ma_donhang");
alter table public."HOA_DON" add constraint "fk_26_HOA_DON" foreign key ("nguoi_lap") references public."NHAN_VIEN" ("ma_nhan_vien");
alter table public."THANH_TOAN" add constraint "fk_27_THANH_TOAN" foreign key ("ma_donhang") references public."DON_HANG" ("ma_donhang");
alter table public."CHUONG_TRINH_KHUYEN_MAI" add constraint "fk_28_CHUONG_TRINH_KHUYEN_MAI" foreign key ("nguoi_tao") references public."NHAN_VIEN" ("ma_nhan_vien");
alter table public."VOUCHER" add constraint "fk_29_VOUCHER" foreign key ("ma_ctkm") references public."CHUONG_TRINH_KHUYEN_MAI" ("ma_ctkm");
alter table public."SU_DUNG_VOUCHER" add constraint "fk_30_SU_DUNG_VOUCHER" foreign key ("ma_voucher") references public."VOUCHER" ("ma_voucher");
alter table public."SU_DUNG_VOUCHER" add constraint "fk_31_SU_DUNG_VOUCHER" foreign key ("ma_donhang") references public."DON_HANG" ("ma_donhang");
create index "idx_ct_don_hang_order" on public."CT_DON_HANG" ("ma_donhang");
create index "idx_ct_don_hang_sku" on public."CT_DON_HANG" ("sku");

-- This project uses FastAPI authorization, not direct browser table access.
alter table public."KHO" enable row level security;
revoke all on table public."KHO" from anon, authenticated;
grant all on table public."KHO" to service_role;
alter table public."NHAN_VIEN" enable row level security;
revoke all on table public."NHAN_VIEN" from anon, authenticated;
grant all on table public."NHAN_VIEN" to service_role;
alter table public."TAI_KHOAN" enable row level security;
revoke all on table public."TAI_KHOAN" from anon, authenticated;
grant all on table public."TAI_KHOAN" to service_role;
alter table public."KHACH_HANG" enable row level security;
revoke all on table public."KHACH_HANG" from anon, authenticated;
grant all on table public."KHACH_HANG" to service_role;
alter table public."LOAI_SP" enable row level security;
revoke all on table public."LOAI_SP" from anon, authenticated;
grant all on table public."LOAI_SP" to service_role;
alter table public."SAN_PHAM" enable row level security;
revoke all on table public."SAN_PHAM" from anon, authenticated;
grant all on table public."SAN_PHAM" to service_role;
alter table public."TON_KHO" enable row level security;
revoke all on table public."TON_KHO" from anon, authenticated;
grant all on table public."TON_KHO" to service_role;
alter table public."NHA_CUNG_CAP" enable row level security;
revoke all on table public."NHA_CUNG_CAP" from anon, authenticated;
grant all on table public."NHA_CUNG_CAP" to service_role;
alter table public."PHIEU_NHAP" enable row level security;
revoke all on table public."PHIEU_NHAP" from anon, authenticated;
grant all on table public."PHIEU_NHAP" to service_role;
alter table public."CT_PHIEU_NHAP" enable row level security;
revoke all on table public."CT_PHIEU_NHAP" from anon, authenticated;
grant all on table public."CT_PHIEU_NHAP" to service_role;
alter table public."PHIEU_CHUYEN_KHO" enable row level security;
revoke all on table public."PHIEU_CHUYEN_KHO" from anon, authenticated;
grant all on table public."PHIEU_CHUYEN_KHO" to service_role;
alter table public."CT_CHUYEN_KHO" enable row level security;
revoke all on table public."CT_CHUYEN_KHO" from anon, authenticated;
grant all on table public."CT_CHUYEN_KHO" to service_role;
alter table public."DON_HANG" enable row level security;
revoke all on table public."DON_HANG" from anon, authenticated;
grant all on table public."DON_HANG" to service_role;
alter table public."CT_DON_HANG" enable row level security;
revoke all on table public."CT_DON_HANG" from anon, authenticated;
grant all on table public."CT_DON_HANG" to service_role;
alter table public."HOA_DON" enable row level security;
revoke all on table public."HOA_DON" from anon, authenticated;
grant all on table public."HOA_DON" to service_role;
alter table public."THANH_TOAN" enable row level security;
revoke all on table public."THANH_TOAN" from anon, authenticated;
grant all on table public."THANH_TOAN" to service_role;
alter table public."CHUONG_TRINH_KHUYEN_MAI" enable row level security;
revoke all on table public."CHUONG_TRINH_KHUYEN_MAI" from anon, authenticated;
grant all on table public."CHUONG_TRINH_KHUYEN_MAI" to service_role;
alter table public."VOUCHER" enable row level security;
revoke all on table public."VOUCHER" from anon, authenticated;
grant all on table public."VOUCHER" to service_role;
alter table public."SU_DUNG_VOUCHER" enable row level security;
revoke all on table public."SU_DUNG_VOUCHER" from anon, authenticated;
grant all on table public."SU_DUNG_VOUCHER" to service_role;
grant usage, select on all sequences in schema public to service_role;
commit;

