-- Audit trail for every committed stock quantity change.
-- Apply after migrations 001-004.

create table if not exists public."LICH_SU_TON_KHO" (
  "ma_lich_su" int generated by default as identity primary key,
  "ma_kho" int not null references public."KHO" ("ma_kho"),
  "sku" varchar not null references public."SAN_PHAM" ("sku"),
  "loai_giao_dich" varchar not null,
  "so_luong_thay_doi" int not null,
  "so_luong_truoc" int not null,
  "so_luong_sau" int not null,
  "ma_tham_chieu" varchar,
  "nguoi_thuc_hien" varchar,
  "tao_luc" timestamptz not null default now(),
  "ghi_chu" text
);

create index if not exists "idx_lich_su_ton_kho_kho_time"
  on public."LICH_SU_TON_KHO" ("ma_kho", "tao_luc" desc);
create index if not exists "idx_lich_su_ton_kho_sku_time"
  on public."LICH_SU_TON_KHO" ("sku", "tao_luc" desc);

create or replace function public.log_stock_movement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  operation varchar := coalesce(nullif(current_setting('phub.stock_operation', true), ''), 'CAP_NHAT_TON');
  reference varchar := nullif(current_setting('phub.stock_reference', true), '');
  actor varchar := nullif(current_setting('phub.stock_actor', true), '');
begin
  if coalesce(new."so_luong_ton", 0) = coalesce(old."so_luong_ton", 0) then
    return new;
  end if;
  insert into public."LICH_SU_TON_KHO"
    ("ma_kho", "sku", "loai_giao_dich", "so_luong_thay_doi", "so_luong_truoc", "so_luong_sau", "ma_tham_chieu", "nguoi_thuc_hien")
  values
    (new."ma_kho", new."sku", operation, new."so_luong_ton" - old."so_luong_ton", old."so_luong_ton", new."so_luong_ton", reference, actor);
  return new;
end;
$$;

drop trigger if exists "trg_log_stock_movement" on public."TON_KHO";
create trigger "trg_log_stock_movement"
after update of "so_luong_ton" on public."TON_KHO"
for each row execute function public.log_stock_movement();

alter table public."LICH_SU_TON_KHO" enable row level security;
revoke all on table public."LICH_SU_TON_KHO" from anon, authenticated;
grant all on table public."LICH_SU_TON_KHO" to service_role;
grant usage, select on sequence public."LICH_SU_TON_KHO_ma_lich_su_seq" to service_role;
