-- LOCAL TEST CLUSTER ONLY. Minimal promotion/customer schema, not a migration.
CREATE TABLE public."KHACH_HANG"(
    ma_kh varchar PRIMARY KEY,ten_kh varchar NOT NULL,sdt varchar,
    dia_chi_chi_tiet_md varchar,tinh_thanh_md varchar,xa_phuong_md varchar
);
ALTER TABLE public."DON_HANG" ADD COLUMN ma_kh varchar REFERENCES public."KHACH_HANG";
CREATE TABLE public."CHUONG_TRINH_KHUYEN_MAI"(
    ma_ctkm integer PRIMARY KEY,ngay_bat_dau timestamp NOT NULL,ngay_ket_thuc timestamp NOT NULL,trang_thai varchar NOT NULL
);
CREATE TABLE public."VOUCHER"(
    ma_voucher integer PRIMARY KEY,ma_ctkm integer NOT NULL REFERENCES public."CHUONG_TRINH_KHUYEN_MAI",
    ma_code varchar NOT NULL UNIQUE,loai_giam varchar NOT NULL,gia_tri_giam numeric(18,2) NOT NULL,
    giam_toi_da numeric(18,2),gia_tri_don_toi_thieu numeric(18,2) NOT NULL DEFAULT 0,
    gioi_han_tong_luot integer,gioi_han_moi_khach integer,trang_thai varchar NOT NULL
);
CREATE TABLE public."SU_DUNG_VOUCHER"(
    ma_su_dung integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_voucher integer NOT NULL REFERENCES public."VOUCHER",ma_donhang varchar NOT NULL REFERENCES public."DON_HANG",
    so_tien_giam numeric(18,2) NOT NULL,thoi_gian_ap_dung timestamp NOT NULL,trang_thai varchar NOT NULL,thoi_gian_huy timestamp,
    UNIQUE(ma_voucher,ma_donhang)
);
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
