-- Local integration fixture based on the Supabase metadata reviewed for orders.
-- NEVER apply this fixture to a shared database. The test runner creates its own cluster.
CREATE ROLE anon;
CREATE ROLE authenticated;
CREATE ROLE service_role BYPASSRLS;
CREATE TABLE public."LOAI_SP" (ma_loai_sp varchar PRIMARY KEY, trang_thai integer NOT NULL DEFAULT 1);
CREATE TABLE public."SAN_PHAM" (
    ma_sp varchar PRIMARY KEY, sku varchar NOT NULL UNIQUE, ten_sp varchar NOT NULL,
    ma_loai_sp varchar NOT NULL REFERENCES public."LOAI_SP", don_vi varchar NOT NULL,
    gia_ban_hien_tai numeric(18,2) NOT NULL CHECK (gia_ban_hien_tai >= 0), trang_thai integer NOT NULL DEFAULT 1
);
CREATE TABLE public."KHO" (ma_kho integer PRIMARY KEY, trang_thai integer NOT NULL DEFAULT 1);
CREATE TABLE public."TON_KHO" (
    ma_kho integer REFERENCES public."KHO", sku varchar REFERENCES public."SAN_PHAM"(sku),
    so_luong_ton integer NOT NULL CHECK (so_luong_ton >= 0), cap_nhat_luc timestamp,
    PRIMARY KEY (ma_kho, sku)
);
CREATE TABLE public."DON_HANG" (
    ma_donhang varchar PRIMARY KEY, kenh_ban varchar NOT NULL, trang_thai varchar NOT NULL,
    thoi_gian_dat timestamp NOT NULL, ten_nguoi_nhan varchar(100), sdt_nguoi_nhan varchar(20),
    dia_chi_chi_tiet varchar(255), tinh_thanh varchar(100), xa_phuong varchar(100), ghi_chu text
);
CREATE TABLE public."CT_DON_HANG" (
    ma_ct_donhang integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_donhang varchar NOT NULL REFERENCES public."DON_HANG", sku varchar NOT NULL REFERENCES public."SAN_PHAM"(sku),
    ma_kho_xuat integer NOT NULL REFERENCES public."KHO", ten_sp_luc_ban varchar NOT NULL,
    don_vi_luc_ban varchar NOT NULL, so_luong integer NOT NULL CHECK (so_luong > 0),
    don_gia numeric(18,2) NOT NULL, giam_gia numeric(18,2) NOT NULL,
    giam_gia_voucher numeric(18,2) NOT NULL, thue_suat numeric(5,2) NOT NULL,
    tien_thue numeric(18,2) NOT NULL, thanh_tien numeric(18,2) NOT NULL,
    CHECK (thanh_tien = so_luong * don_gia - giam_gia - giam_gia_voucher + tien_thue)
);
GRANT USAGE ON SCHEMA public TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
